# Workflow name
name: Build All Packages

on:
  # Event for the workflow to run on
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

# List of jobs
jobs:
  build:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build all packages (baukasten, website, etc.)
      - name: Build all packages
        run: npm run build

      # Build Storybook
      - name: Build Storybook
        working-directory: packages/baukasten
        env:
          STORYBOOK_BASE_PATH: /baukasten/storybook
          NODE_PATH: ${{ github.workspace }}/packages/baukasten/node_modules
        run: npm run build-storybook

